version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    volumes:
      - "./api:/usr/src/app"
    networks:
      - 20191-ada_adanetwork
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=gitlab/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=gitlab.config.DevelopmentConfig
      - DB_URL=${DB_URL}
      - DB_NAME=${DB_NAME}
      - APP_ID=${APP_ID}
      - APP_SECRET=${APP_SECRET}
      - BOT_NAME=${BOT_NAME}
      - REDIRECT_URI=${REDIRECT_URI}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - WEBHOOK_URL_ENVIRONMENT=${WEBHOOK_URL_ENVIRONMENT}
  mongo-gitlab:
    image: mongo
    command: mongod --port 27010
    volumes:
      - /mongo_gitlab:/data/db
    networks:
      - 20191-ada_adanetwork
    ports:
      - 27010:27010
  cronjob:
    image: joaovitor3/ada-gitlab-cronjob:homolog
    volumes:
      - ./outputs:/cronjob/home
    stdin_open: true
    tty: true
    networks:
      - 20191-ada_adanetwork
    environment:
      - DB_URL=${DB_URL}
      - DB_NAME=${DB_NAME}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
networks:
  20191-ada_adanetwork:
    external: true
    driver: "bridge"
